// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalPortfolioWebSite.Data.Concrete.EntityFramework.Context;

#nullable disable

namespace PersonalPortfolioWebSite.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220823185923_three")]
    partial class three
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PersonalPortfolioWebSite.Entities.Concrete.Models.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CvEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvTurk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("About");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CvEnglish = "Hello, if I need to introduce myself briefly, my name and surname is Ömer Faruk Benli.I was born on 26.02.1993 in Istanbul. My university education, Sakarya University-Labor Economy and Industrial Relations with a GPA of (3.52). After university education, I worked as an assistant real estate appraiser in the private sector for 3.5 years. In 2021 Istarted to take sofwtware trainings with the idea pf dping it in the software industry. Software It focuses on C# as the language, Asp.Net CORE and Angular as the framework, and MsSQL and MongoDB as the database.I create using these technologies. Currently, as a Freelence project, the promotion site of an elevator manufacturer company I'm busy programming it as full-stack. Thanks for visiting my site.     ",
                            CvTurk = "Merhabalar, kendimi kısaca tanıtmam gerekirse adım ve soyadım Ömer Faruk Benli, 26.02.1993 tarihinde, İstanbul'da doğdum. Üniversite eğitimimi, Sakarya Üniversitesi-Çalışma Ekonomisi ve Endüstri İlişkileri Bölümünde, 3.52 not ortalaması ile tamamladım. Üniversite eğitimi sonrası, 3.5 yıl boyunca özel sektörde gayrimenkul değerleme uzman yardımcısı olarak görev yaptım. 2021 yılında yazılım alanında kariyer yapmak düşüncesiyle yazılım eğitimleri almaya başladım. Yazılım dili olarak C#, Framework olarak Asp.Net CORE ve Angular, database olarak ise MsSQL ve MongoDB'ye yoğunlaşmış olup, projelerimi bu teknolojileri kullanarak oluşturmaktayım. Şuan Freelence bir proje olarak, asansör üreticisi bir firmanın tanıtım sitesinin full-stack olarak programlanması konusunda meşgul olmaktayım.Sitemi ziyaret ettiğiniz için teşekkürler.    "
                        });
                });

            modelBuilder.Entity("PersonalPortfolioWebSite.Entities.Concrete.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İstanbul/Ümraniye",
                            Email = "omerfarukbenli@hotmail.com",
                            FullName = "Ömer Faruk Benli",
                            Phone = "0(544) 205 98 45"
                        });
                });

            modelBuilder.Entity("PersonalPortfolioWebSite.Entities.Concrete.Models.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Github")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linkedln")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Youtube")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Home");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Github = "https://github.com/omerfarukbenli",
                            Linkedln = "https://www.linkedin.com/in/%C3%B6mer-faruk-benli-5a6719241/",
                            Youtube = "https://www.youtube.com/channel/UCnlOSRG2OWoXfwbhpMdzTQw"
                        });
                });

            modelBuilder.Entity("PersonalPortfolioWebSite.Entities.Concrete.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Urls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Link");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Subtitle = "Asp.Net CORE 6 - Crud",
                            Title = "Asp.Net CORE 6",
                            Urls = "https://github.com/omerfarukbenli/Asp.Net-6-Crud-Many-to-Many"
                        },
                        new
                        {
                            Id = 2,
                            Subtitle = "Asp.Net CORE 6 - Authantication",
                            Title = "Asp.Net CORE 6",
                            Urls = "https://github.com/omerfarukbenli/Asp.Net-6-Auth"
                        },
                        new
                        {
                            Id = 3,
                            Subtitle = "Angular 14 - Crud",
                            Title = "Angular 14",
                            Urls = "https://github.com/omerfarukbenli/Angular-Crud-islemleri"
                        },
                        new
                        {
                            Id = 4,
                            Subtitle = "MongoDB - Crud",
                            Title = "Asp.Net CORE 6",
                            Urls = "https://github.com/omerfarukbenli/MongoDB-Asp.Net-6-WebApi-Crud"
                        });
                });

            modelBuilder.Entity("PersonalPortfolioWebSite.Entities.Concrete.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeaturedImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlHandle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("PersonalPortfolioWebSite.Entities.Concrete.Models.Repo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContentSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Repo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentSummary = "C# ile Algoritma 101",
                            Title = "Turkcell Geleceği Yazanlar",
                            Url = "../assets/images/s1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ContentSummary = "#C ile Algoritma 201",
                            Title = "Turkcell Geleceği Yazanlar",
                            Url = "../assets/images/s2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            ContentSummary = "Web Programlama 101",
                            Title = "Turkcell Geleceği Yazanlar",
                            Url = "../assets/images/s3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ContentSummary = "Web Programlama 201",
                            Title = "Turkcell Geleceği Yazanlar",
                            Url = "../assets/images/s4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            ContentSummary = "Web Programlama 301",
                            Title = "Turkcell Geleceği Yazanlar",
                            Url = "../assets/images/s5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            ContentSummary = "Asp.Net CORE 6-Angular 14",
                            Title = "Bilgi Teknolojileri Kurumu Akademi",
                            Url = "../assets/images/s6.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
